package genetics;

/**
 * @author Krzysztof Spytkowski
 * @date 6th April 2014
 */
public enum CrossingOverType {
    ONEPOINTWITHTWOCHILDREN, ONEPOINTWITHONECHILD, UNIFORMCROSSOVER, WEIGHTEDUNIFORMCROSSOVER, TWOPOINTSWITHTWOCHILDREN, TWOPOINTSWITHONECHILD
}
