package genetics;

/**
 * @author Krzysztof Spytkowski
 * @date 6 kwi 2014
 */
public enum CrossingOverType {
    ONEPOINTWITHTWOCHILDREN, ONEPOINTWITHONECHILD, UNIFORMCROSSOVER, WEIGHTEDUNIFORMCROSSOVER, TWOPOINTSWITHTWOCHILDREN, TWOPOINTSWITHONECHILD
}
